### ISSUE TITLE
Results: shown increase in walking and cycling at the zone level

### ISSUE THREAD

**Issue by Robinlovelace** [spstreets/OD2017#23]
![image](https://user-images.githubusercontent.com/1825120/156445169-b41ef448-bf2d-4de7-b2b5-77b5c72a14e0.png)

**Comment by Robinlovelace** [comment]
E.g. above.

**Comment by fred-r-ramos** [comment]
Hi! Sorry my ignorance. I want to replicate this trips-simulation.R. Where can I find the input data. I see that it uses a piggyback.

**Comment by Robinlovelace** [comment]
Hi @fred-r-ramos you should be able to find them here: https://github.com/spstreets/OD2017/releases 

FYI I'm off on holiday until Monday so will go a bit quiet on this this week.
