### ISSUE TITLE
Cenário de Curto-Prazo

### ISSUE THREAD

**Issue by lucasccdias** [spstreets/OD2017#25]
Placeholder to communicate about the Near Market scenario.

**Comment by Robinlovelace** [comment]
Great stuff, let's chat about this next when I'm back.

**Comment by Robinlovelace** [comment]
Approach:

- Train model estimating cycling and walking using this function (note: it does not work for v. large distances): https://github.com/ITSLeeds/pct/blob/HEAD/R/model.R
- Subset OD pairs that are are outliers compared with the model
- Retrain the model on the subset of data with high walking + cycling levels

Another approach is to train a model based on OD pairs originating in an area with high levels of walking and cycling.

**Comment by Robinlovelace** [comment]
Idea from @fred-r-ramos: train the model on long walking trips.

**Comment by Robinlovelace** [comment]
So we get around a doubling in cycling.
