### ISSUE TITLE
A/B Street changes + report

### ISSUE THREAD

**Issue by dabreegster** [spstreets/OD2017#27]
Just carving out a place to track all of the A/B Street work.

- [ ] Map the baseline sidewalk widths in abst from the gpkg
- [x] Map the proposed sidewalk widths in abst from Hannah's PDFs
- [ ] Fix the distribution of walking speeds (currently uniformly distributed between 2-3mph)
- [x] Make the overall traffic patterns in SMP look more reasonable. (Right now, the main road totally halts for tens of minutes as pedestrians stream freely across crosswalks. This could be a combination of map edits for crosswalks and stop signs, and maybe some code for more realistic crossing behavior.)
- [ ] Simulate more driving trips (we cancel 80% of driving trips to avoid total gridlock right now)
- [x] Run the A/B test and verify total overcrowding events decreases
- [x] Create a new risk exposure UI that shows relative numbers of problems on the map (maybe as two heatmaps -- one showing areas with less problems, another with more? maybe just one grid?)
- [ ] Figure out why overcrowding increases in some areas
- [x] Add a layer showing current people / square meter

**Comment by dabreegster** [comment]
# Report notes

- definition of the crowded sidewalks / risk exposure
- walking speed (no elevation)
- how the demand model was produced, but only 80% of cars
- zebras vs unmarked crossings
- stop sign policies (and other things affecting ordering)
- feedback loop of overcrowded sidewalk (spend more time in a crowded area)
- why fixing one area might push the problem somewhere else
- **the spurious diff caveat** (also try to solve that)
- compare throughput with Hannah's report

**Comment by dabreegster** [comment]
https://user-images.githubusercontent.com/1664407/165754714-70da6f7f-29b0-4101-bc1a-690b28f707ff.mp4

@lucasccdias / @fred-r-ramos , I have a question about pedestrian/vehicle behavior in Brazil. In this situation, we have an intersection with no stop signs, and zebra crossings crossing Avenida Marchal Tito. In the video above, pedestrians freely stream across the intersection, blocking traffic for a long time. This doesn't seem realistic to me.

1) No stop signs + zebra crossing = what happens in practice?
2) No stop signs + no zebra = vehicles have priority (in practice; I don't think we're interested in modelling legal rights)
3) At stop signs, I'd expect roughly some round-robin / first-come, first-serve ordering. Some pedestrians might cross in batches or start crossing a bit late if cars are stopped.

**Comment by Robinlovelace** [comment]
All this sounds good to me, syncing abst with local knowledge key to success, I can be an observer/writer of the outputs.
