### ISSUE TITLE
Expand area of Sao Miguel Paulista

### ISSUE THREAD

**Issue by Robinlovelace** [spstreets/OD2017#29]

**Comment by lucasccdias** [comment]
- [ ] 2km buffer
- [ ] Update the `.json` scenario.

**Comment by dabreegster** [comment]
Some observations from A/B Street:

- The industrial area at the top of the map doesn't get the small service roads imported, so users will notice strange floating pedestrians there. The buildings have driveways snapped to the nearest road the south or east, but the effect is quite strange:
![Screenshot from 2022-05-05 11-51-17](https://user-images.githubusercontent.com/1664407/166909968-8b836050-9eb2-496b-996e-ea31eb2b4aff.png)
- I still need to cancel about 80% of driving trips to have any hope of not gridlocking. There are really bizarre results though. At noon, 8000 people are walking around, but there are only 45 cars on the road. Does that sound reasonable at all?
- Most of the overcrowding hot-spots jump to https://www.openstreetmap.org/node/1989882078, which is purely a consequence of the network topology. The rail line divides things, and anybody entering the map from the northwest corner is forced to cross this pedestrian bridge.
- The larger scenario is slower to run.

I'll keep trying to fix bugs and get a meaningful report written based on the smaller study area for now. The larger area introduces more complications that might just be distractions, so I won't prioritize working through all of those just yet.
